[project]
name = "py-openapi2md"
version = "0.1.0"
description = "OpenAPI to Markdown generator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jsf>=0.11.2",
    "pyinstaller>=6.16.0",
]

[project.scripts]
openapi2md = "openapi2md.__main__:main"
