[project]
name = "py-openapi"
version = "0.1.0"
description = "OpenAPI to Markdown generator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jsf>=0.11.2",
    "pyinstaller>=6.16.0",
]
